package com.stocksugg.db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Stock database access. Defaults to PostgreSQL; use {@link DatabaseConfig#h2File()} for the legacy
 * embedded H2 store under {@code ./data/stocksugg}.
 */
public final class Database implements AutoCloseable {

    private final Connection connection;
    private final boolean postgres;

    public Database() throws SQLException {
        this(DatabaseConfig.load());
    }

    public Database(DatabaseConfig config) throws SQLException {
        this(config.jdbcUrl(), config.user(), config.password());
    }

    /** JDBC URL with credentials resolved from config (H2 tests use sa/empty). */
    public Database(String jdbcUrl) throws SQLException {
        this(
                jdbcUrl,
                jdbcUrl.startsWith("jdbc:h2:") ? DatabaseConfig.H2_USER : DatabaseConfig.load().user(),
                jdbcUrl.startsWith("jdbc:h2:") ? DatabaseConfig.H2_PASSWORD : DatabaseConfig.load().password());
    }

    public Database(String jdbcUrl, String user, String password) throws SQLException {
        this.postgres = jdbcUrl.startsWith("jdbc:postgresql:");
        ensureDriverLoaded(jdbcUrl);
        this.connection = DriverManager.getConnection(jdbcUrl, user, password);
        initSchema();
    }

    public Connection connection() {
        return connection;
    }

    /**
     * Tomcat's webapp classloader often needs an explicit driver load; ServiceLoader alone
     * is unreliable when the driver JAR lives under {@code WEB-INF/lib}.
     */
    private static void ensureDriverLoaded(String jdbcUrl) throws SQLException {
        try {
            if (jdbcUrl.startsWith("jdbc:postgresql:")) {
                Class.forName("org.postgresql.Driver");
            } else if (jdbcUrl.startsWith("jdbc:h2:")) {
                Class.forName("org.h2.Driver");
            }
        } catch (ClassNotFoundException e) {
            throw new SQLException("JDBC driver not found for URL: " + jdbcUrl, e);
        }
    }

    private void initSchema() throws SQLException {
        try (Statement stmt = connection.createStatement()) {
            if (postgres) {
                initPostgresSchema(stmt);
            } else {
                initH2Schema(stmt);
            }
        }
    }

    private static void initPostgresSchema(Statement stmt) throws SQLException {
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS stock (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ticker VARCHAR(10) NOT NULL,
                    "date" VARCHAR(10) NOT NULL,
                    open REAL,
                    high REAL,
                    low REAL,
                    close REAL,
                    ma5 REAL,
                    ma10 REAL,
                    ma20 REAL,
                    ma50 REAL,
                    ma200 REAL,
                    rsi14 REAL,
                    chandemmt REAL,
                    chalkinmf REAL,
                    suggestedaction VARCHAR(16),
                    confidence REAL,
                    suggestedstopprice REAL,
                    suggestedentryprice REAL,
                    suggestedprofitprice REAL,
                    thesis TEXT,
                    risks TEXT
                )
                """);
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS rsi14 REAL");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedaction VARCHAR(16)");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS confidence REAL");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedstopprice REAL");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedentryprice REAL");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedprofitprice REAL");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS thesis TEXT");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS risks TEXT");
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS admin (
                    id INTEGER,
                    "key" VARCHAR(100),
                    "value" TEXT
                )
                """);
        // Existing installs may still have VARCHAR(155); widen for long TICKERS lists.
        stmt.execute("ALTER TABLE admin ALTER COLUMN \"value\" TYPE TEXT");
        initTuningAndSuggestionsPostgres(stmt);
    }

    private static void initH2Schema(Statement stmt) throws SQLException {
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS stock (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ticker VARCHAR(10) NOT NULL,
                    "date" VARCHAR(10) NOT NULL,
                    open FLOAT,
                    high FLOAT,
                    low FLOAT,
                    close FLOAT,
                    ma5 FLOAT,
                    ma10 FLOAT,
                    ma20 FLOAT,
                    ma50 FLOAT,
                    ma200 FLOAT,
                    rsi14 FLOAT,
                    chandeMmt FLOAT,
                    chalkinMF FLOAT,
                    suggestedAction VARCHAR(16),
                    confidence FLOAT,
                    suggestedStopPrice FLOAT,
                    suggestedEntryPrice FLOAT,
                    suggestedProfitPrice FLOAT,
                    thesis TEXT,
                    risks TEXT
                )
                """);
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS rsi14 FLOAT");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedAction VARCHAR(16)");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS confidence FLOAT");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedStopPrice FLOAT");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedEntryPrice FLOAT");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedProfitPrice FLOAT");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS thesis TEXT");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS risks TEXT");
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS admin (
                    id INTEGER,
                    "key" VARCHAR(100),
                    "value" TEXT
                )
                """);
        // H2: widen existing VARCHAR columns when present (no-op if already TEXT).
        try {
            stmt.execute("ALTER TABLE admin ALTER COLUMN \"value\" SET DATA TYPE TEXT");
        } catch (SQLException ignored) {
            // Fresh TEXT column or dialect difference — CREATE IF NOT EXISTS already covers new DBs.
        }
        initTuningAndSuggestionsH2(stmt);
    }

    /**
     * Parameter combinations for Gemini tuning experiments, plus versioned suggestion rows
     * linked to {@code stock.id} and {@code tuning_params.id}.
     */
    private static void initTuningAndSuggestionsPostgres(Statement stmt) throws SQLException {
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS tuning_params (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    num_date_point INTEGER DEFAULT 40,
                    ma5_weight INTEGER DEFAULT 1,
                    ma10_weight INTEGER DEFAULT 1,
                    ma20_weight INTEGER DEFAULT 1,
                    ma50_weight INTEGER DEFAULT 1,
                    ma200_weight INTEGER DEFAULT 1,
                    rsi_weight INTEGER DEFAULT 1,
                    cmo_weight INTEGER DEFAULT 1,
                    cmf_weight INTEGER DEFAULT 1,
                    name VARCHAR(100),
                    description TEXT
                )
                """);
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS suggestions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    stock_id BIGINT,
                    param_id BIGINT,
                    suggestedaction VARCHAR(16),
                    confidence REAL,
                    suggestedstopprice REAL,
                    suggestedentryprice REAL,
                    suggestedprofitprice REAL,
                    thesis TEXT,
                    risks TEXT
                )
                """);
        // Safe if the table already existed without this index (manual create or older schema).
        stmt.execute("""
                CREATE UNIQUE INDEX IF NOT EXISTS suggestions_stock_param_uidx
                ON suggestions (stock_id, param_id)
                """);
        seedDefaultTuningParams(stmt);
        initStrategyOptimizePostgres(stmt);
    }

    private static void initTuningAndSuggestionsH2(Statement stmt) throws SQLException {
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS tuning_params (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    num_date_point INTEGER DEFAULT 40,
                    ma5_weight INTEGER DEFAULT 1,
                    ma10_weight INTEGER DEFAULT 1,
                    ma20_weight INTEGER DEFAULT 1,
                    ma50_weight INTEGER DEFAULT 1,
                    ma200_weight INTEGER DEFAULT 1,
                    rsi_weight INTEGER DEFAULT 1,
                    cmo_weight INTEGER DEFAULT 1,
                    cmf_weight INTEGER DEFAULT 1,
                    name VARCHAR(100),
                    description VARCHAR(4000)
                )
                """);
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS suggestions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    stock_id BIGINT,
                    param_id BIGINT,
                    suggestedAction VARCHAR(16),
                    confidence FLOAT,
                    suggestedStopPrice FLOAT,
                    suggestedEntryPrice FLOAT,
                    suggestedProfitPrice FLOAT,
                    thesis VARCHAR(4000),
                    risks VARCHAR(4000)
                )
                """);
        stmt.execute("""
                CREATE UNIQUE INDEX IF NOT EXISTS suggestions_stock_param_uidx
                ON suggestions (stock_id, param_id)
                """);
        seedDefaultTuningParams(stmt);
        initStrategyOptimizeH2(stmt);
    }

    private static void initStrategyOptimizePostgres(Statement stmt) throws SQLException {
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS strategy_optimize (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ticker VARCHAR(10) NOT NULL,
                    param_id BIGINT NOT NULL REFERENCES tuning_params(id),
                    from_date DATE NOT NULL,
                    to_date DATE NOT NULL,
                    starting_cash DOUBLE PRECISION NOT NULL DEFAULT 10000,
                    parts INTEGER NOT NULL,
                    min_buy_confidence DOUBLE PRECISION NOT NULL,
                    min_sell_confidence DOUBLE PRECISION NOT NULL,
                    on_buy VARCHAR(16) NOT NULL,
                    on_sell VARCHAR(16) NOT NULL,
                    on_hold VARCHAR(16) NOT NULL DEFAULT 'NONE',
                    on_avoid VARCHAR(16) NOT NULL,
                    ending_equity DOUBLE PRECISION NOT NULL,
                    ending_cash DOUBLE PRECISION,
                    ending_shares INTEGER,
                    last_close DOUBLE PRECISION,
                    return_pct DOUBLE PRECISION NOT NULL,
                    buy_count INTEGER,
                    sell_count INTEGER,
                    skipped_buys INTEGER,
                    buy_hold_equity DOUBLE PRECISION,
                    buy_hold_return_pct DOUBLE PRECISION,
                    rank INTEGER NOT NULL DEFAULT 1,
                    computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """);
        stmt.execute("""
                CREATE UNIQUE INDEX IF NOT EXISTS strategy_optimize_uq
                ON strategy_optimize (ticker, param_id, from_date, to_date, rank)
                """);
    }

    private static void initStrategyOptimizeH2(Statement stmt) throws SQLException {
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS strategy_optimize (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ticker VARCHAR(10) NOT NULL,
                    param_id BIGINT NOT NULL,
                    from_date DATE NOT NULL,
                    to_date DATE NOT NULL,
                    starting_cash DOUBLE PRECISION NOT NULL DEFAULT 10000,
                    parts INTEGER NOT NULL,
                    min_buy_confidence DOUBLE PRECISION NOT NULL,
                    min_sell_confidence DOUBLE PRECISION NOT NULL,
                    on_buy VARCHAR(16) NOT NULL,
                    on_sell VARCHAR(16) NOT NULL,
                    on_hold VARCHAR(16) NOT NULL DEFAULT 'NONE',
                    on_avoid VARCHAR(16) NOT NULL,
                    ending_equity DOUBLE PRECISION NOT NULL,
                    ending_cash DOUBLE PRECISION,
                    ending_shares INTEGER,
                    last_close DOUBLE PRECISION,
                    return_pct DOUBLE PRECISION NOT NULL,
                    buy_count INTEGER,
                    sell_count INTEGER,
                    skipped_buys INTEGER,
                    buy_hold_equity DOUBLE PRECISION,
                    buy_hold_return_pct DOUBLE PRECISION,
                    rank INTEGER NOT NULL DEFAULT 1,
                    computed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        stmt.execute("""
                CREATE UNIQUE INDEX IF NOT EXISTS strategy_optimize_uq
                ON strategy_optimize (ticker, param_id, from_date, to_date, rank)
                """);
    }

    /** One baseline row so experiments always have a default param_id. */
    private static void seedDefaultTuningParams(Statement stmt) throws SQLException {
        try (var rs = stmt.executeQuery("SELECT COUNT(*) FROM tuning_params")) {
            if (rs.next() && rs.getInt(1) > 0) {
                return;
            }
        }
        stmt.execute("""
                INSERT INTO tuning_params (
                    num_date_point, ma5_weight, ma10_weight, ma20_weight, ma50_weight, ma200_weight,
                    rsi_weight, cmo_weight, cmf_weight, name, description
                ) VALUES (
                    40, 1, 1, 1, 1, 1, 1, 1, 1,
                    'DEFAULT-40',
                    'Baseline: 40 lookback bars, equal indicator weights'
                )
                """);
    }

    /** Returns true if the {@code stock} table exists. */
    public boolean stockTableExists() throws SQLException {
        return tableExists(postgres ? "stock" : "STOCK");
    }

    /** Returns true if the {@code admin} table exists. */
    public boolean adminTableExists() throws SQLException {
        return tableExists(postgres ? "admin" : "ADMIN");
    }

    /** Returns true if the {@code tuning_params} table exists. */
    public boolean tuningParamsTableExists() throws SQLException {
        return tableExists(postgres ? "tuning_params" : "TUNING_PARAMS");
    }

    /** Returns true if the {@code suggestions} table exists. */
    public boolean suggestionsTableExists() throws SQLException {
        return tableExists(postgres ? "suggestions" : "SUGGESTIONS");
    }

    /** Returns true if the {@code strategy_optimize} table exists. */
    public boolean strategyOptimizeTableExists() throws SQLException {
        return tableExists(postgres ? "strategy_optimize" : "STRATEGY_OPTIMIZE");
    }

    private boolean tableExists(String tablePattern) throws SQLException {
        try (var rs = connection.getMetaData().getTables(null, null, tablePattern, new String[] {"TABLE"})) {
            return rs.next();
        }
    }

    @Override
    public void close() throws SQLException {
        connection.close();
    }
}
