package com.stocksugg.db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Stock database access. Defaults to PostgreSQL; use {@link DatabaseConfig#h2File()} for the legacy
 * embedded H2 store under {@code ./data/stocksugg}.
 */
public final class Database implements AutoCloseable {

    private final Connection connection;
    private final boolean postgres;

    public Database() throws SQLException {
        this(DatabaseConfig.load());
    }

    public Database(DatabaseConfig config) throws SQLException {
        this(config.jdbcUrl(), config.user(), config.password());
    }

    /** JDBC URL with credentials resolved from config (H2 tests use sa/empty). */
    public Database(String jdbcUrl) throws SQLException {
        this(
                jdbcUrl,
                jdbcUrl.startsWith("jdbc:h2:") ? DatabaseConfig.H2_USER : DatabaseConfig.load().user(),
                jdbcUrl.startsWith("jdbc:h2:") ? DatabaseConfig.H2_PASSWORD : DatabaseConfig.load().password());
    }

    public Database(String jdbcUrl, String user, String password) throws SQLException {
        this.postgres = jdbcUrl.startsWith("jdbc:postgresql:");
        ensureDriverLoaded(jdbcUrl);
        this.connection = DriverManager.getConnection(jdbcUrl, user, password);
        initSchema();
    }

    public Connection connection() {
        return connection;
    }

    /**
     * Tomcat's webapp classloader often needs an explicit driver load; ServiceLoader alone
     * is unreliable when the driver JAR lives under {@code WEB-INF/lib}.
     */
    private static void ensureDriverLoaded(String jdbcUrl) throws SQLException {
        try {
            if (jdbcUrl.startsWith("jdbc:postgresql:")) {
                Class.forName("org.postgresql.Driver");
            } else if (jdbcUrl.startsWith("jdbc:h2:")) {
                Class.forName("org.h2.Driver");
            }
        } catch (ClassNotFoundException e) {
            throw new SQLException("JDBC driver not found for URL: " + jdbcUrl, e);
        }
    }

    private void initSchema() throws SQLException {
        try (Statement stmt = connection.createStatement()) {
            if (postgres) {
                initPostgresSchema(stmt);
            } else {
                initH2Schema(stmt);
            }
        }
    }

    private static void initPostgresSchema(Statement stmt) throws SQLException {
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS stock (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ticker VARCHAR(10) NOT NULL,
                    "date" VARCHAR(10) NOT NULL,
                    open REAL,
                    high REAL,
                    low REAL,
                    close REAL,
                    ma5 REAL,
                    ma10 REAL,
                    ma20 REAL,
                    ma50 REAL,
                    ma200 REAL,
                    chandemmt REAL,
                    chalkinmf REAL,
                    suggestedaction VARCHAR(16),
                    confidence REAL,
                    suggestedstopprice REAL,
                    suggestedentryprice REAL,
                    suggestedprofitprice REAL,
                    thesis TEXT,
                    risks TEXT
                )
                """);
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedaction VARCHAR(16)");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS confidence REAL");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedstopprice REAL");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedentryprice REAL");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedprofitprice REAL");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS thesis TEXT");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS risks TEXT");
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS admin (
                    id INTEGER,
                    "key" VARCHAR(100),
                    "value" VARCHAR(155)
                )
                """);
    }

    private static void initH2Schema(Statement stmt) throws SQLException {
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS stock (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ticker VARCHAR(10) NOT NULL,
                    "date" VARCHAR(10) NOT NULL,
                    open FLOAT,
                    high FLOAT,
                    low FLOAT,
                    close FLOAT,
                    ma5 FLOAT,
                    ma10 FLOAT,
                    ma20 FLOAT,
                    ma50 FLOAT,
                    ma200 FLOAT,
                    chandeMmt FLOAT,
                    chalkinMF FLOAT,
                    suggestedAction VARCHAR(16),
                    confidence FLOAT,
                    suggestedStopPrice FLOAT,
                    suggestedEntryPrice FLOAT,
                    suggestedProfitPrice FLOAT,
                    thesis TEXT,
                    risks TEXT
                )
                """);
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedAction VARCHAR(16)");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS confidence FLOAT");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedStopPrice FLOAT");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedEntryPrice FLOAT");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS suggestedProfitPrice FLOAT");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS thesis TEXT");
        stmt.execute("ALTER TABLE stock ADD COLUMN IF NOT EXISTS risks TEXT");
        stmt.execute("""
                CREATE TABLE IF NOT EXISTS admin (
                    id INTEGER,
                    "key" VARCHAR(100),
                    "value" VARCHAR(155)
                )
                """);
    }

    /** Returns true if the {@code stock} table exists. */
    public boolean stockTableExists() throws SQLException {
        return tableExists(postgres ? "stock" : "STOCK");
    }

    /** Returns true if the {@code admin} table exists. */
    public boolean adminTableExists() throws SQLException {
        return tableExists(postgres ? "admin" : "ADMIN");
    }

    private boolean tableExists(String tablePattern) throws SQLException {
        try (var rs = connection.getMetaData().getTables(null, null, tablePattern, new String[] {"TABLE"})) {
            return rs.next();
        }
    }

    @Override
    public void close() throws SQLException {
        connection.close();
    }
}
